---
name: "Setup Mustache Templates in Bash"
description: |
  This action installs Mustache Templates in Bash
author: martoc
runs:
  using: "composite"
  steps:
    - name: Install Mustache Templates
      shell: bash
      run: |
        curl -sSL https://raw.githubusercontent.com/tests-always-included/mo/refs/tags/3.0.5/mo -o mo
        chmod +x mo
        sudo mv mo /usr/local/bin/
